[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]                                     
clap = { version = "4.4.11", features = ["cargo"] }
clap_complete = "4.4.4"                            
gh = { path = "../gh" }
